spring:
  datasource:
##    h2
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

#    mysql
#    url: jdbc:mysql://localhost:3306/dawn?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
#    username: root
#    password: "0000"
#    driver-class-name: com.mysql.cj.jdbc.Driver

#    docker
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


    h2:
      console:
        enabled: true

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

logging.level:
  org.hibernate.SQL: debug

jwt:
  secret: my-secret-key-should-be-long-enough-256bit

fastapi:
  url: http://127.0.0.1:8000/chat

server:
  address: 0.0.0.0

rag:
  api:
    url: http://rag-api:8000/chat

letter:
  api:
    url: http://rag-api:8000/generate-letter