spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create}  # 기본값은 create
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: ${JWT_SECRET}

fastapi:
  url: ${FASTAPI_URL:http://127.0.0.1:8000/chat}  # 로컬 실행 대비 기본값 유지

server:
  address: 0.0.0.0

rag:
  api:
    url: ${RAG_API_URL}

letter:
  api:
    url: ${LETTER_API_URL}