spring:
  datasource:
#    h2
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

#    mysql
#    url: jdbc:mysql://localhost:3306/dawn?serverTimezone=Asia/Seoul&useSSL=false
#    username: root
#    password: qkfka1396
#    driver-class-name: com.mysql.cj.jdbc.Driver

    #docker
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver


    h2:
      console:
        enabled: true

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

logging.level:
  org.hibernate.SQL: debug

jwt:
  secret: my-secret-key-should-be-long-enough-256bit

